In [2]:
import numpy as np
from numpy import linalg as LA

In [3]:
# исходные данные
# первая матрица
A1 = [[177.2000,   1.0500,   -8.9700,  0.7500],
      [  4.2600, 185.8000,    0.1300, -8.8600],
      [ -3.8100,   5.2300, -189.0000, -4.8800],
      [  5.8200,   3.8700,   -2.4700, 81.4000]]

B1 = [[  455.3400],
      [ -924.0400],
      [-1554.4600],
      [   59.7500]]

# точный результат для первой матрицы
X1 = [[ 3],
      [-5], 
      [ 8], 
      [ 1]]

# вторая матрица
A2 = [[ 167.9400,  32.6700,  -24.9250,  60.2720],
      [ -11.1360,   6.4340,    1.4070,  10.2960],
      [1174.1800, 228.6900, -174.2750, 421.9040],
      [  27.9650,   0.0000,   -3.9950,   0.9990]]

B2 = [[ -9.9130], 
      [-28.7890], 
      [-70.1910], 
      [ 16.9790]]

# точный результат для второй матрицы
X2 = [[ 1], 
      [-5], 
      [ 3], 
      [ 1]]

# единичная матрица
E = [[1, 0, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 1, 0],
     [0, 0, 0, 1]]

In [4]:
# функция для преобразования матрицы к треугольному виду
def gauss_func(matrix):
    # функция меняет матрицу через побочные эффекты
    for nrow, row in enumerate(matrix):
        # nrow равен номеру строки
        # row содержит саму строку матрицы
        divider = row[nrow] # диагональный элемент
        # делим на диагональный элемент.
        row /= divider
        # теперь надо вычесть приведённую строку из всех нижележащих строчек
        for lower_row in matrix[nrow+1:]:
            factor = lower_row[nrow] # элемент строки в колонке nrow
            lower_row -= factor*row # вычитаем, чтобы получить ноль в колонке nrow
    # все строки матрицы изменились, в принципе, можно и не возвращать
    return matrix

# функция, с которой доводим полученную матрицу до единичной
def make_identity(matrix):
    # перебор строк в обратном порядке 
    for nrow in range(len(matrix)-1,0,-1):
        row = matrix[nrow]
        for upper_row in matrix[:nrow]:
            factor = upper_row[nrow]
            upper_row -= factor*row
    return matrix

In [5]:
# функция для нахождения норм
def norm(a):
    norm_one = LA.norm(a, 1)
    norm_inf = LA.norm(a, np.inf)
    return [norm_one, norm_inf]

In [6]:
# функция для нахождения числа обусловленности
def cond(a):
    cond_one = LA.norm(a, 1) * LA.norm(LA.pinv(a), 1)
    cond_inf = LA.norm(a, np.inf) * LA.norm(LA.pinv(a), np.inf)
    return [cond_one, cond_inf]

In [23]:
# функция решения СЛАУ
def solve(A, B):
    AB = np.append(A, B, axis=1)
    return make_identity(gauss_func(np.copy(AB)))[:,4:]

In [24]:
# Решение первого уравнения
F1 = solve(A1, B1)
F1

array([[ 3.],
       [-5.],
       [ 8.],
       [ 1.]])

In [25]:
# Решение второго уравнения
F2 = solve(A2, B2)
F2

array([[ 1.        ],
       [-5.        ],
       [ 2.99999998],
       [ 1.        ]])

In [26]:
# невязка первой матрицы
R1 = B1 - np.matmul(A1, F1)
R1

array([[ 5.68434189e-14],
       [-1.13686838e-13],
       [ 2.27373675e-13],
       [ 7.10542736e-15]])

In [27]:
# невязка второй матрицы
R2 = B2 - np.matmul(A2, F2)
R2

array([[ 2.48689958e-14],
       [-3.55271368e-15],
       [-8.52651283e-14],
       [ 7.10542736e-15]])

In [28]:
# нормы невязки (единичная и бесконечная) первой СЛАУ
norm(R1)

[4.050093593832571e-13, 2.2737367544323206e-13]

In [29]:
# нормы невязки (единичная и бесконечная) второй СЛАУ
norm(R2)

[1.2079226507921703e-13, 8.526512829121202e-14]

In [30]:
# абсолютная погрешность (по единичной и бесконечной нормам) для первой матрицы
norm(F1 - X1)

[2.886579864025407e-15, 1.7763568394002505e-15]

In [31]:
# абсолютная погрешность (по единичной и бесконечной нормам) для второй матрицы
norm(F2 - X2)

[2.2363939922165343e-08, 1.909211277961731e-08]

In [32]:
# относительная погрешность
np.array(norm(F1 - X1)) / np.array(norm(X1))

array([1.69798816e-16, 2.22044605e-16])

In [33]:
# относительная погрешность
np.array(norm(F2 - X2)) / np.array(norm(X2))

array([2.23639399e-09, 3.81842256e-09])

In [34]:
# нахождение обратной матрицы к A1
solve(A1, E)

array([[ 5.64046909e-03, -2.28982519e-05, -2.66793419e-04,
        -7.04567839e-05],
       [-1.48299110e-04,  5.37067465e-03,  3.07252601e-06,
         5.86122797e-04],
       [-1.07493345e-04,  1.55507424e-04, -5.28189253e-03,
        -2.98737343e-04],
       [-3.99497802e-04, -2.48982060e-04, -1.41344318e-04,
         1.22531189e-02]])

In [35]:
np.matmul(A1, A1_1)

array([[ 1.00000000e+00,  4.87890978e-19,  1.31323988e-17,
         4.33680869e-19],
       [-1.18552293e-18,  1.00000000e+00,  1.71189961e-19,
         7.06917513e-18],
       [ 4.64984796e-18, -1.19747521e-18,  1.00000000e+00,
         1.25469628e-17],
       [ 5.05832460e-18,  3.24677019e-18,  1.27821874e-18,
         1.00000000e+00]])

In [36]:
# нахождение обратной матрицы к A2
solve(A2, E)

array([[-1.83004719e+05, -3.26699999e+05,  3.53349599e+04,
        -5.14711991e+05],
       [-3.63749999e+04, -6.53499999e+04,  7.03499998e+03,
        -1.02960000e+05],
       [-1.28106804e+06, -2.28689999e+06,  2.47349719e+05,
        -3.60298394e+06],
       [-1.39964965e+02,  3.98251462e-07,  1.99949950e+01,
         1.00100163e+00]])

In [37]:
np.matmul(A2, A2_1)

array([[ 1.00000000e+00,  9.47600334e-09,  1.87135851e-09,
        -1.06364478e-08],
       [-1.09991128e-10,  9.99999999e-01, -6.50713017e-11,
         4.58309340e-10],
       [ 2.74683419e-08,  7.90397022e-08,  1.00000001e+00,
        -1.59159979e-07],
       [ 1.89721089e-10,  1.63060333e-09,  1.36906714e-10,
         9.99999997e-01]])

In [38]:
# числа обусловленности первой системы
cond(A1)

[2.6492159819385415, 2.6466740188618796]

In [39]:
# числа обусловленности
cond(A2)

[5829659542.270575, 14829547446.326979]