In [2]:
import numpy as np
from numpy import linalg as LA

In [115]:
# исходные данные
# первая матрица
A1 = [[177.2000,   1.0500,   -8.9700,  0.7500],
      [  4.2600, 185.8000,    0.1300, -8.8600],
      [ -3.8100,   5.2300, -189.0000, -4.8800],
      [  5.8200,   3.8700,   -2.4700, 81.4000]]

B1 = [[  455.3400],
      [ -924.0400],
      [-1554.4600],
      [   59.7500]]

# точный результат для первой матрицы
X1 = [[ 3],
      [-5], 
      [ 8], 
      [ 1]]

# вторая матрица
A2 = [[ 167.9400,  32.6700,  -24.9250,  60.2720],
      [ -11.1360,   6.4340,    1.4070,  10.2960],
      [1174.1800, 228.6900, -174.2750, 421.9040],
      [  27.9650,   0.0000,   -3.9950,   0.9990]]

B2 = [[ -9.9130], 
      [-28.7890], 
      [-70.1910], 
      [ 16.9790]]

# точный результат для второй матрицы
X2 = [[ 1], 
      [-5], 
      [ 3], 
      [ 1]]

# единичная матрица
E = [[1, 0, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 1, 0],
     [0, 0, 0, 1]]

In [95]:
# функция для преобразования матрицы к треугольному виду
def gauss_func(matrix):
    # функция меняет матрицу через побочные эффекты
    for nrow, row in enumerate(matrix):
        # nrow равен номеру строки
        # row содержит саму строку матрицы
        divider = row[nrow] # диагональный элемент
        # делим на диагональный элемент.
        row /= divider
        # теперь надо вычесть приведённую строку из всех нижележащих строчек
        for lower_row in matrix[nrow+1:]:
            factor = lower_row[nrow] # элемент строки в колонке nrow
            lower_row -= factor*row # вычитаем, чтобы получить ноль в колонке nrow
    # все строки матрицы изменились, в принципе, можно и не возвращать
    return matrix

# функция, с которой доводим полученную матрицу до единичной
def make_identity(matrix):
    # перебор строк в обратном порядке 
    for nrow in range(len(matrix)-1,0,-1):
        row = matrix[nrow]
        for upper_row in matrix[:nrow]:
            factor = upper_row[nrow]
            upper_row -= factor*row
    return matrix

In [79]:
# функция для нахождения норм
def norm(a):
    norm_one = LA.norm(a, 1)
    norm_inf = LA.norm(a, np.inf)
    return [norm_one, norm_inf]

In [80]:
# функция для нахождения числа обусловленности
def cond(a):
    cond_one = LA.norm(a, 1) * LA.norm(LA.pinv(a), 1)
    cond_inf = LA.norm(a, np.inf) * LA.norm(LA.pinv(a), np.inf)
    return [cond_one, cond_inf]

In [85]:
# функция решения СЛАУ
def solve(A, B):
    AB = np.append(A1, B, axis=1)
    return make_identity(gaussFunc(np.copy(AB)))[:,4:]

In [96]:
# Решение первого уравнения
F1 = solve(A1, B1)
F1

array([[ 3.],
       [-5.],
       [ 8.],
       [ 1.]])

In [97]:
# Решение второго уравнения
F2 = solve(A2, B2)
F2

array([[-0.03772454],
       [-0.14341015],
       [ 0.36225774],
       [ 0.22909497]])

In [110]:
# невязка первой матрицы
R1 = B1 - np.matmul(A1, F1)
R1

array([[ 5.68434189e-14],
       [-1.13686838e-13],
       [ 2.27373675e-13],
       [ 7.10542736e-15]])

In [114]:
# невязка второй матрицы
R2 = B2 - np.matmul(A2, F2)
R2

array([[ -3.67106912],
       [-31.15485806],
       [-26.62274973],
       [ 19.25232057]])

In [118]:
# нормы невязки (единичная и бесконечная) первой СЛАУ
norm1 = norm(R1)
norm1

[4.050093593832571e-13, 2.2737367544323206e-13]

In [119]:
norm2 = norm(R2)
norm2

[80.70099747309769, 31.15485806105682]